# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  template: template0
  username: ubuntu
  password: password
  
development:
  <<: *default
  database: blocmetrics_development
  
test:
  <<: *default
  database: blocmetrics_test

production:
  <<: *default
  database: blocmetrics_production
  username: blocmetrics
  password: <%= ENV['BLOCMETRICS_DATABASE_PASSWORD'] %>
